name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to (e.g., qa, staging)'
        required: true
        type: choice
        options:
        - qa
        - uat
        - staging

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Set environment variables
      run: |
        if [ "${{ github.event.inputs.environment }}" == "qa" ]; then
          echo "BASE_URL=${{ secrets.QA_BASE_URL }}" >> $GITHUB_ENV
          echo "ADMIN_USERNAME=${{ secrets.QA_ADMIN_USERNAME }}" >> $GITHUB_ENV
          echo "ADMIN_PASSWORD=${{ secrets.QA_ADMIN_PASSWORD }}" >> $GITHUB_ENV
        elif [ "${{ github.event.inputs.environment }}" == "uat" ]; then
          echo "BASE_URL=${{ secrets.UAT_BASE_URL }}" >> $GITHUB_ENV
          echo "ADMIN_USERNAME=${{ secrets.UAT_ADMIN_USERNAME }}" >> $GITHUB_ENV
          echo "ADMIN_PASSWORD=${{ secrets.UAT_ADMIN_PASSWORD }}" >> $GITHUB_ENV
        elif [ "${{ github.event.inputs.environment }}" == "staging" ]; then
          echo "BASE_URL=${{ secrets.STAGING_BASE_URL }}" >> $GITHUB_ENV
          echo "ADMIN_USERNAME=${{ secrets.STAGING_ADMIN_USERNAME }}" >> $GITHUB_ENV
          echo "ADMIN_PASSWORD=${{ secrets.STAGING_ADMIN_PASSWORD }}" >> $GITHUB_ENV
        fi

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      timeout-minutes: 30
      env:
        BASE_URL: ${{ env.BASE_URL }}
        ADMIN_USERNAME: ${{ env.ADMIN_USERNAME }}
        ADMIN_PASSWORD: ${{ env.ADMIN_PASSWORD }}
      run: npx playwright test

    - name: Ensure Playwright report directory exists
      run: mkdir -p playwright-report

    - name: Upload Playwright report
      if: ${{ success() && !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30